// Copyright 2016 The gRPC Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Hand-committed descriptors of the standard gRPC Server Reflection Protocol
// (https://github.com/grpc/grpc/blob/master/doc/server-reflection.md), produced
// by `protoc-gen-es` from the canonical
// `grpc/reflection/{v1,v1alpha}/reflection.proto` (Copyright 2016 The gRPC
// Authors, Apache-2.0). The protocol is frozen, so the descriptors are vendored
// instead of generated at build time.
//
// Only the service descriptors are needed: the connect router and the wire
// codecs resolve against the `FileDescriptorProto` below, and this package
// models the reflection messages with Effect `Schema` in `GrpcReflection.ts`.

import type { DescService } from "@bufbuild/protobuf";
import { fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file grpc/reflection/v1/reflection.proto.
 */
const file_grpc_reflection_v1_reflection = fileDesc(
  "CiNncnBjL3JlZmxlY3Rpb24vdjEvcmVmbGVjdGlvbi5wcm90bxISZ3JwYy5yZWZsZWN0aW9uLnYxIoUCChdTZXJ2ZXJSZWZsZWN0aW9uUmVxdWVzdBIMCgRob3N0GAEgASgJEhoKEGZpbGVfYnlfZmlsZW5hbWUYAyABKAlIABIgChZmaWxlX2NvbnRhaW5pbmdfc3ltYm9sGAQgASgJSAASSQoZZmlsZV9jb250YWluaW5nX2V4dGVuc2lvbhgFIAEoCzIkLmdycGMucmVmbGVjdGlvbi52MS5FeHRlbnNpb25SZXF1ZXN0SAASJwodYWxsX2V4dGVuc2lvbl9udW1iZXJzX29mX3R5cGUYBiABKAlIABIXCg1saXN0X3NlcnZpY2VzGAcgASgJSABCEQoPbWVzc2FnZV9yZXF1ZXN0IkUKEEV4dGVuc2lvblJlcXVlc3QSFwoPY29udGFpbmluZ190eXBlGAEgASgJEhgKEGV4dGVuc2lvbl9udW1iZXIYAiABKAUiuAMKGFNlcnZlclJlZmxlY3Rpb25SZXNwb25zZRISCgp2YWxpZF9ob3N0GAEgASgJEkUKEG9yaWdpbmFsX3JlcXVlc3QYAiABKAsyKy5ncnBjLnJlZmxlY3Rpb24udjEuU2VydmVyUmVmbGVjdGlvblJlcXVlc3QSTgoYZmlsZV9kZXNjcmlwdG9yX3Jlc3BvbnNlGAQgASgLMiouZ3JwYy5yZWZsZWN0aW9uLnYxLkZpbGVEZXNjcmlwdG9yUmVzcG9uc2VIABJVCh5hbGxfZXh0ZW5zaW9uX251bWJlcnNfcmVzcG9uc2UYBSABKAsyKy5ncnBjLnJlZmxlY3Rpb24udjEuRXh0ZW5zaW9uTnVtYmVyUmVzcG9uc2VIABJJChZsaXN0X3NlcnZpY2VzX3Jlc3BvbnNlGAYgASgLMicuZ3JwYy5yZWZsZWN0aW9uLnYxLkxpc3RTZXJ2aWNlUmVzcG9uc2VIABI7Cg5lcnJvcl9yZXNwb25zZRgHIAEoCzIhLmdycGMucmVmbGVjdGlvbi52MS5FcnJvclJlc3BvbnNlSABCEgoQbWVzc2FnZV9yZXNwb25zZSI3ChZGaWxlRGVzY3JpcHRvclJlc3BvbnNlEh0KFWZpbGVfZGVzY3JpcHRvcl9wcm90bxgBIAMoDCJLChdFeHRlbnNpb25OdW1iZXJSZXNwb25zZRIWCg5iYXNlX3R5cGVfbmFtZRgBIAEoCRIYChBleHRlbnNpb25fbnVtYmVyGAIgAygFIksKE0xpc3RTZXJ2aWNlUmVzcG9uc2USNAoHc2VydmljZRgBIAMoCzIjLmdycGMucmVmbGVjdGlvbi52MS5TZXJ2aWNlUmVzcG9uc2UiHwoPU2VydmljZVJlc3BvbnNlEgwKBG5hbWUYASABKAkiOgoNRXJyb3JSZXNwb25zZRISCgplcnJvcl9jb2RlGAEgASgFEhUKDWVycm9yX21lc3NhZ2UYAiABKAkyiQEKEFNlcnZlclJlZmxlY3Rpb24SdQoUU2VydmVyUmVmbGVjdGlvbkluZm8SKy5ncnBjLnJlZmxlY3Rpb24udjEuU2VydmVyUmVmbGVjdGlvblJlcXVlc3QaLC5ncnBjLnJlZmxlY3Rpb24udjEuU2VydmVyUmVmbGVjdGlvblJlc3BvbnNlKAEwAUJmChVpby5ncnBjLnJlZmxlY3Rpb24udjFCFVNlcnZlclJlZmxlY3Rpb25Qcm90b1ABWjRnb29nbGUuZ29sYW5nLm9yZy9ncnBjL3JlZmxlY3Rpb24vZ3JwY19yZWZsZWN0aW9uX3YxYgZwcm90bzM",
);

/**
 * Describes the file grpc/reflection/v1alpha/reflection.proto.
 */
const file_grpc_reflection_v1alpha_reflection = fileDesc(
  "CihncnBjL3JlZmxlY3Rpb24vdjFhbHBoYS9yZWZsZWN0aW9uLnByb3RvEhdncnBjLnJlZmxlY3Rpb24udjFhbHBoYSKKAgoXU2VydmVyUmVmbGVjdGlvblJlcXVlc3QSDAoEaG9zdBgBIAEoCRIaChBmaWxlX2J5X2ZpbGVuYW1lGAMgASgJSAASIAoWZmlsZV9jb250YWluaW5nX3N5bWJvbBgEIAEoCUgAEk4KGWZpbGVfY29udGFpbmluZ19leHRlbnNpb24YBSABKAsyKS5ncnBjLnJlZmxlY3Rpb24udjFhbHBoYS5FeHRlbnNpb25SZXF1ZXN0SAASJwodYWxsX2V4dGVuc2lvbl9udW1iZXJzX29mX3R5cGUYBiABKAlIABIXCg1saXN0X3NlcnZpY2VzGAcgASgJSABCEQoPbWVzc2FnZV9yZXF1ZXN0IkUKEEV4dGVuc2lvblJlcXVlc3QSFwoPY29udGFpbmluZ190eXBlGAEgASgJEhgKEGV4dGVuc2lvbl9udW1iZXIYAiABKAUi0QMKGFNlcnZlclJlZmxlY3Rpb25SZXNwb25zZRISCgp2YWxpZF9ob3N0GAEgASgJEkoKEG9yaWdpbmFsX3JlcXVlc3QYAiABKAsyMC5ncnBjLnJlZmxlY3Rpb24udjFhbHBoYS5TZXJ2ZXJSZWZsZWN0aW9uUmVxdWVzdBJTChhmaWxlX2Rlc2NyaXB0b3JfcmVzcG9uc2UYBCABKAsyLy5ncnBjLnJlZmxlY3Rpb24udjFhbHBoYS5GaWxlRGVzY3JpcHRvclJlc3BvbnNlSAASWgoeYWxsX2V4dGVuc2lvbl9udW1iZXJzX3Jlc3BvbnNlGAUgASgLMjAuZ3JwYy5yZWZsZWN0aW9uLnYxYWxwaGEuRXh0ZW5zaW9uTnVtYmVyUmVzcG9uc2VIABJOChZsaXN0X3NlcnZpY2VzX3Jlc3BvbnNlGAYgASgLMiwuZ3JwYy5yZWZsZWN0aW9uLnYxYWxwaGEuTGlzdFNlcnZpY2VSZXNwb25zZUgAEkAKDmVycm9yX3Jlc3BvbnNlGAcgASgLMiYuZ3JwYy5yZWZsZWN0aW9uLnYxYWxwaGEuRXJyb3JSZXNwb25zZUgAQhIKEG1lc3NhZ2VfcmVzcG9uc2UiNwoWRmlsZURlc2NyaXB0b3JSZXNwb25zZRIdChVmaWxlX2Rlc2NyaXB0b3JfcHJvdG8YASADKAwiSwoXRXh0ZW5zaW9uTnVtYmVyUmVzcG9uc2USFgoOYmFzZV90eXBlX25hbWUYASABKAkSGAoQZXh0ZW5zaW9uX251bWJlchgCIAMoBSJQChNMaXN0U2VydmljZVJlc3BvbnNlEjkKB3NlcnZpY2UYASADKAsyKC5ncnBjLnJlZmxlY3Rpb24udjFhbHBoYS5TZXJ2aWNlUmVzcG9uc2UiHwoPU2VydmljZVJlc3BvbnNlEgwKBG5hbWUYASABKAkiOgoNRXJyb3JSZXNwb25zZRISCgplcnJvcl9jb2RlGAEgASgFEhUKDWVycm9yX21lc3NhZ2UYAiABKAkykwEKEFNlcnZlclJlZmxlY3Rpb24SfwoUU2VydmVyUmVmbGVjdGlvbkluZm8SMC5ncnBjLnJlZmxlY3Rpb24udjFhbHBoYS5TZXJ2ZXJSZWZsZWN0aW9uUmVxdWVzdBoxLmdycGMucmVmbGVjdGlvbi52MWFscGhhLlNlcnZlclJlZmxlY3Rpb25SZXNwb25zZSgBMAFCcAoaaW8uZ3JwYy5yZWZsZWN0aW9uLnYxYWxwaGFCFVNlcnZlclJlZmxlY3Rpb25Qcm90b1ABWjlnb29nbGUuZ29sYW5nLm9yZy9ncnBjL3JlZmxlY3Rpb24vZ3JwY19yZWZsZWN0aW9uX3YxYWxwaGFiBnByb3RvMw",
);

/**
 * Describes the service grpc.reflection.v1.ServerReflection.
 */
export const ServerReflectionV1: DescService =
  file_grpc_reflection_v1_reflection.services.find(
    (service) => service.typeName === "grpc.reflection.v1.ServerReflection",
  )!;

/**
 * Describes the service grpc.reflection.v1alpha.ServerReflection.
 */
export const ServerReflectionV1Alpha: DescService =
  file_grpc_reflection_v1alpha_reflection.services.find(
    (service) =>
      service.typeName === "grpc.reflection.v1alpha.ServerReflection",
  )!;
