import { analyzeFileUsage, fieldValueOccurrences } from "./fileUsage.js";
import { generateClient } from "./generateClient.js";
import { generateRegistry } from "./generateRegistry.js";
import { generateSchemas } from "./generateSchemas.js";
import { generateServer } from "./generateServer.js";
import { effectImportPath, pbImportPath } from "./naming.js";
import type { GeneratorFile } from "./types.js";

interface ImportGroup {
  readonly protoFileName: string;
  readonly messages: ReadonlyArray<string>;
  readonly enums: ReadonlyArray<string>;
}

/** Imported message and enum names, grouped by the proto file declaring them. */
const importGroups = (file: GeneratorFile): ReadonlyArray<ImportGroup> => {
  const groups = new Map<
    string,
    { readonly messages: Set<string>; readonly enums: Set<string> }
  >();
  const record = (
    importedFrom: string | undefined,
    name: string,
    kind: "message" | "enum",
  ) => {
    if (importedFrom === undefined) return;
    const group = groups.get(importedFrom) ?? {
      messages: new Set<string>(),
      enums: new Set<string>(),
    };
    if (kind === "message") group.messages.add(name);
    else group.enums.add(name);
    groups.set(importedFrom, group);
  };

  for (const message of file.messages) {
    for (const field of message.fields) {
      for (const { value } of fieldValueOccurrences(field)) {
        if (value.kind === "message") {
          record(value.importedFrom, value.messageName, "message");
        } else if (value.kind === "enum") {
          record(value.importedFrom, value.enumName, "enum");
        }
      }
    }
  }
  for (const service of file.services) {
    for (const method of service.methods) {
      for (const type of [method.inputType, method.outputType]) {
        record(type.importedFrom, type.name, "message");
      }
    }
  }
  return [...groups.entries()].map(([protoFileName, group]) => ({
    protoFileName,
    messages: [...group.messages].sort(),
    enums: [...group.enums].sort(),
  }));
};

export const generateFile = (
  file: GeneratorFile,
  importExtension: "js" | "ts" = "js",
): string => {
  const usage = analyzeFileUsage(file);
  const pbImport = pbImportPath(file.protoFileName, importExtension);
  const descriptorImports = file.services.map((service) => service.name);
  const effectImports = [
    ...(usage.hasServices ? ["Context", "Effect", "Layer"] : []),
    "Schema",
    ...(usage.usesStream ? ["Stream"] : []),
  ];
  // Generated code no longer touches Effect RPC on either side: clients
  // depend on the `GrpcInvoker` seam and servers publish their handlers
  // through `GrpcServerProtocol.handlersEffect`. Message-only files still
  // need `CodegenSupport.readField` for their converters.
  const effectGrpcImports = [
    ...(usage.hasServices || usage.readsFields ? ["CodegenSupport"] : []),
    ...(usage.hasServices
      ? [
          "GrpcInvoker",
          "GrpcMethodRegistry",
          "GrpcServerProtocol",
          "GrpcStatusError",
        ]
      : []),
  ];

  const lines = [
    "// @generated by protoc-gen-effect-grpc. DO NOT EDIT.",
    "",
    ...(usage.usesBase64Bytes ? ['import { Buffer } from "node:buffer";'] : []),
    ...(usage.jsonWellKnownImports.length > 0
      ? [
          'import { fromJson as protobufFromJson, toJson as protobufToJson } from "@bufbuild/protobuf";',
          "import {",
          ...usage.jsonWellKnownImports.map(
            ([name, alias]) => `  ${name} as ${alias},`,
          ),
          '} from "@bufbuild/protobuf/wkt";',
        ]
      : []),
    `import { ${effectImports.join(", ")} } from "effect";`,
    ...(effectGrpcImports.length > 0
      ? [
          `import { ${effectGrpcImports.join(", ")} } from "@effect-grpc/effect-grpc";`,
        ]
      : []),
    ...(usage.hasServices
      ? [
          "import {",
          ...descriptorImports.map((item) => `  ${item},`),
          `} from "${pbImport}";`,
        ]
      : []),
    // The bare `type` aliases are only emitted when the generated code
    // references them (see `FileUsage.usedImportedTypes`); everything else in
    // the file derives its types from the imported `Schema`/`from`/`to`
    // symbols, and an unreferenced alias fails `noUnusedLocals` in consumers.
    ...importGroups(file).flatMap((imported) => [
      "import {",
      ...imported.enums.flatMap((enumName) => [
        `  ${enumName}Schema,`,
        ...(usage.usedImportedTypes.has(enumName)
          ? [`  type ${enumName},`]
          : []),
      ]),
      ...imported.messages.flatMap((message) => [
        `  ${message}Schema,`,
        `  from${message},`,
        `  to${message},`,
        ...(usage.usedImportedTypes.has(message) ? [`  type ${message},`] : []),
      ]),
      `} from "${effectImportPath(file.protoFileName, imported.protoFileName, importExtension)}";`,
    ]),
    "",
    ...generateSchemas(file, usage),
    ...generateRegistry(file, usage),
    ...generateClient(file),
    ...generateServer(file),
  ];

  return `${lines.join("\n").trimEnd()}\n`;
};
