import { analyzeFileUsage } from "./fileUsage.js";
import { generateClient } from "./generateClient.js";
import { generateRegistry } from "./generateRegistry.js";
import { generateRpcs } from "./generateRpcs.js";
import { generateSchemas } from "./generateSchemas.js";
import { generateServer } from "./generateServer.js";
import { effectImportPath, pbImportPath } from "./naming.js";
import type { GeneratorFile } from "./types.js";

export const generateFile = (file: GeneratorFile): string => {
  const usage = analyzeFileUsage(file);
  const pbImport = pbImportPath(file.protoFileName, file.importExtension);
  const descriptorImports = file.services.map((service) => service.name);
  const effectImports = [
    ...(usage.hasServices ? ["Context", "Effect", "Layer"] : []),
    "Schema",
    ...(usage.usesStream ? ["Stream"] : []),
  ];
  const rpcImports = [
    ...(usage.hasRpcMethods ? ["Rpc", "RpcClient"] : []),
    "RpcClientError",
    "RpcGroup",
  ];
  const effectGrpcImports = [
    "CodegenSupport",
    ...(usage.hasStreamingMethods ? ["GrpcClientProtocol"] : []),
    "GrpcMethodRegistry",
    ...(usage.hasStreamingMethods ? ["GrpcServerProtocol"] : []),
    "GrpcStatusError",
  ];

  const lines = [
    "// @generated by protoc-gen-effect-grpc. DO NOT EDIT.",
    "",
    ...(usage.usesBase64Bytes ? ['import { Buffer } from "node:buffer";'] : []),
    ...(usage.jsonWellKnownImports.length > 0
      ? [
          'import { fromJson as protobufFromJson, toJson as protobufToJson } from "@bufbuild/protobuf";',
          "import {",
          ...usage.jsonWellKnownImports.map(
            ([name, alias]) => `  ${name} as ${alias},`,
          ),
          '} from "@bufbuild/protobuf/wkt";',
        ]
      : []),
    `import { ${effectImports.join(", ")} } from "effect";`,
    ...(usage.hasServices
      ? [
          `import { ${rpcImports.join(", ")} } from "effect/unstable/rpc";`,
          `import { ${effectGrpcImports.join(", ")} } from "@effect-grpc/effect-grpc";`,
          "import {",
          ...descriptorImports.map((item) => `  ${item},`),
          `} from "${pbImport}";`,
        ]
      : []),
    // The bare `type` aliases are only emitted when the generated code
    // references them (see `FileUsage.usedImportedTypes`); everything else in
    // the file derives its types from the imported `Schema`/`from`/`to`
    // symbols, and an unreferenced alias fails `noUnusedLocals` in consumers.
    ...file.imports.flatMap((imported) => [
      "import {",
      ...imported.enums.flatMap((enumName) => [
        `  ${enumName}Schema,`,
        ...(usage.usedImportedTypes.has(enumName)
          ? [`  type ${enumName},`]
          : []),
      ]),
      ...imported.messages.flatMap((message) => [
        `  ${message}Schema,`,
        `  from${message},`,
        `  to${message},`,
        ...(usage.usedImportedTypes.has(message) ? [`  type ${message},`] : []),
      ]),
      `} from "${effectImportPath(file.protoFileName, imported.protoFileName, file.importExtension)}";`,
    ]),
    "",
    ...generateSchemas(file, usage),
    ...generateRpcs(file),
    ...generateRegistry(file, usage),
    ...generateClient(file),
    ...generateServer(file),
  ];

  return `${lines.join("\n").trimEnd()}\n`;
};
