import { generateClient } from "./generateClient.js";
import { generateRegistry, usesBase64Bytes } from "./generateRegistry.js";
import { generateRpcs } from "./generateRpcs.js";
import { generateSchemas } from "./generateSchemas.js";
import { generateServer } from "./generateServer.js";
import { effectImportPath, pbImportPath } from "./naming.js";
import {
  isRequestStreaming,
  type FieldModel,
  type FieldValueModel,
  type GeneratorFile,
} from "./types.js";
import { wellKnownJsonSchemaName } from "./wellKnown.js";

export const generateFile = (file: GeneratorFile): string => {
  const pbImport = pbImportPath(file.protoFileName, file.importExtension);
  const descriptorImports = file.services.map((service) => service.name);
  const hasServices = file.services.length > 0;
  const hasRpcMethods = file.services.some((service) =>
    service.methods.some((method) => !isRequestStreaming(method)),
  );
  const hasStreamingMethods = file.services.some((service) =>
    service.methods.some(isRequestStreaming),
  );
  const jsonWellKnownImports = jsonWellKnownSchemaImports(file);
  const needsBuffer = usesBase64Bytes(file);
  const effectImports = [
    ...(hasServices ? ["Context", "Effect", "Layer"] : []),
    "Schema",
    ...(hasServices ? ["Stream"] : []),
  ];
  const rpcImports = [
    ...(hasRpcMethods ? ["Rpc", "RpcClient"] : []),
    "RpcClientError",
    "RpcGroup",
  ];
  const effectGrpcImports = [
    "CodegenSupport",
    ...(hasStreamingMethods ? ["GrpcClientProtocol"] : []),
    "GrpcMethodRegistry",
    ...(hasStreamingMethods ? ["GrpcServerProtocol"] : []),
    "GrpcStatusError",
  ];

  const lines = [
    "// @generated by protoc-gen-effect-grpc. DO NOT EDIT.",
    "",
    ...(needsBuffer ? ['import { Buffer } from "node:buffer";'] : []),
    ...(jsonWellKnownImports.length > 0
      ? [
          'import { fromJson as protobufFromJson, toJson as protobufToJson } from "@bufbuild/protobuf";',
          "import {",
          ...jsonWellKnownImports.map(
            ([name, alias]) => `  ${name} as ${alias},`,
          ),
          '} from "@bufbuild/protobuf/wkt";',
        ]
      : []),
    `import { ${effectImports.join(", ")} } from "effect";`,
    ...(hasServices
      ? [
          `import { ${rpcImports.join(", ")} } from "@effect/rpc";`,
          `import { ${effectGrpcImports.join(", ")} } from "@effect-grpc/effect-grpc";`,
          "import {",
          ...descriptorImports.map((item) => `  ${item},`),
          `} from "${pbImport}";`,
        ]
      : []),
    ...file.imports.flatMap((imported) => [
      "import {",
      ...imported.enums.flatMap((enumName) => [
        `  ${enumName}Schema,`,
        `  type ${enumName},`,
      ]),
      ...imported.messages.flatMap((message) => [
        `  ${message}Schema,`,
        `  from${message},`,
        `  to${message},`,
        `  type ${message},`,
      ]),
      `} from "${effectImportPath(file.protoFileName, imported.protoFileName, file.importExtension)}";`,
    ]),
    "",
    ...generateSchemas(file),
    ...generateRpcs(file),
    ...generateRegistry(file),
    ...generateClient(file),
    ...generateServer(file),
  ];

  return `${lines.join("\n").trimEnd()}\n`;
};

const jsonWellKnownSchemaImports = (
  file: GeneratorFile,
): ReadonlyArray<readonly [string, string]> => {
  const aliases = new Map<string, string>();
  for (const field of file.messages.flatMap((message) => message.fields)) {
    for (const value of fieldValues(field)) {
      if (value.kind !== "well-known") continue;
      const alias = wellKnownJsonSchemaName(value.type);
      if (alias) aliases.set(alias.replace(/^Protobuf/, ""), alias);
    }
  }
  for (const service of file.services) {
    for (const method of service.methods) {
      for (const typeName of [method.inputType, method.outputType]) {
        const alias = ["Struct", "Value", "ListValue", "FieldMask"].find(
          (name) => typeName === `GrpcGoogleProtobuf${name}`,
        );
        if (alias) aliases.set(`${alias}Schema`, `Protobuf${alias}Schema`);
      }
    }
  }
  return [...aliases.entries()].sort(([left], [right]) =>
    left.localeCompare(right),
  );
};

const fieldValues = (field: FieldModel): ReadonlyArray<FieldValueModel> => {
  switch (field.kind) {
    case "scalar":
    case "message":
    case "enum":
    case "well-known":
      return [field];
    case "list":
      return [field.item];
    case "map":
      return [field.value];
    case "oneof":
      return field.cases.map((oneofCase) => oneofCase.value);
  }
};
